---@class ConnectionModule
---@field init_host fun()
---@field init_client fun(connectionData: ConnectionData): boolean
---@field send_game_data fun(data: table)
---@field start_game fun(color: string)
---@field end_game fun()
---@field update fun()

---@class ConnectionData
---@field name string
---@field key string?
