---@class CoordinatesModule
---@field init fun(color: string)
---@field translate fun(pos: Position): number, number
---@field draw fun(screenW: number, screenH: number, squareW: number, squareH: number, columnW: number)
