---@class GameModule
---@field init fun(color: string)
---@field start fun(pieces: Piece[][])
---@field release fun()
---@field continue_playing fun()
---@field on_mouse_moved fun(x: number, y: number): boolean
---@field on_mouse_pressed fun(x: number, y: number, button: number)
---@field update fun(data: table)
---@field draw fun()

---@class Game
---@field board Square[][]
---@field pieces table<string, Piece[]>
