---@class InputBoxModule
---@field new fun(self: InputBoxModule, x: number, y: number, w: number, h: number, fontSize: number, limit: number?): InputBox

---@class InputBox: Widget
---@field x number
---@field y number
---@field w number
---@field h number
---@field text table
---@field state string
---@field limit number
---@field callback function
---@field font love.Font
