---@class Modules
---@field game GameModule
---@field hud HudModule
---@field menu MenuModule
---@field button ButtonModule
---@field label LabelModule
---@field panel PanelModule
---@field inputBox InputBoxModule
---@field coordinates CoordinatesModule
---@field board BoardModule
---@field square SquareModule
---@field interface PieceModule
---@field connection ConnectionModule
---@field window WindowModule
---@field font FontModule
---@field piece PieceModule
