---@class ReadwriteModule
---@field get_user_name fun(): string
---@field set_user_name fun(name: string)
---@field get_saved_connections fun(): ConnectionData[]
---@field save_connection fun(newConnection: ConnectionData)
