---@class Widget
---@field on_mouse_moved fun(widget: Widget, x: number, y: number): boolean
---@field on_mouse_pressed fun(widget: Widget): boolean
---@field on_text_input fun(widget: Widget, char: string)
---@field on_key_pressed fun(widget: Widget, key: string): boolean
---@field draw fun(widget: Widget)
