return {
    white = {
        [1] = {
            ["A"] = { type = "rook", color = "black" },
            ["B"] = { type = "knight", color = "black" },
            ["C"] = { type = "bishop", color = "black" },
            ["D"] = { type = "queen", color = "black" },
            ["E"] = { type = "king", color = "black" },
            ["F"] = { type = "bishop", color = "black" },
            ["G"] = { type = "knight", color = "black" },
            ["H"] = { type = "rook", color = "black" },
        },
        [2] = {
            ["A"] = { type = "pawn", color = "black" },
            ["B"] = { type = "pawn", color = "black" },
            ["C"] = { type = "pawn", color = "black" },
            ["D"] = { type = "pawn", color = "black" },
            ["E"] = { type = "pawn", color = "black" },
            ["F"] = { type = "pawn", color = "black" },
            ["G"] = { type = "pawn", color = "black" },
            ["H"] = { type = "pawn", color = "black" },
        },
        [7] = {
            ["A"] = { type = "pawn", color = "white" },
            ["B"] = { type = "pawn", color = "white" },
            ["C"] = { type = "pawn", color = "white" },
            ["D"] = { type = "pawn", color = "white" },
            ["E"] = { type = "pawn", color = "white" },
            ["F"] = { type = "pawn", color = "white" },
            ["G"] = { type = "pawn", color = "white" },
            ["H"] = { type = "pawn", color = "white" },
        },
        [8] = {
            ["A"] = { type = "rook", color = "white" },
            ["B"] = { type = "knight", color = "white" },
            ["C"] = { type = "bishop", color = "white" },
            ["D"] = { type = "queen", color = "white" },
            ["E"] = { type = "king", color = "white" },
            ["F"] = { type = "bishop", color = "white" },
            ["G"] = { type = "knight", color = "white" },
            ["H"] = { type = "rook", color = "white" },
        }
    },
    black = {
        [1] = {
            ["A"] = { type = "rook", color = "white" },
            ["B"] = { type = "knight", color = "white" },
            ["C"] = { type = "bishop", color = "white" },
            ["D"] = { type = "king", color = "white" },
            ["E"] = { type = "queen", color = "white" },
            ["F"] = { type = "bishop", color = "white" },
            ["G"] = { type = "knight", color = "white" },
            ["H"] = { type = "rook", color = "white" },
        },
        [2] = {
            ["A"] = { type = "pawn", color = "white" },
            ["B"] = { type = "pawn", color = "white" },
            ["C"] = { type = "pawn", color = "white" },
            ["D"] = { type = "pawn", color = "white" },
            ["E"] = { type = "pawn", color = "white" },
            ["F"] = { type = "pawn", color = "white" },
            ["G"] = { type = "pawn", color = "white" },
            ["H"] = { type = "pawn", color = "white" },
        },
        [7] = {
            ["A"] = { type = "pawn", color = "black" },
            ["B"] = { type = "pawn", color = "black" },
            ["C"] = { type = "pawn", color = "black" },
            ["D"] = { type = "pawn", color = "black" },
            ["E"] = { type = "pawn", color = "black" },
            ["F"] = { type = "pawn", color = "black" },
            ["G"] = { type = "pawn", color = "black" },
            ["H"] = { type = "pawn", color = "black" },
        },
        [8] = {
            ["A"] = { type = "rook", color = "black" },
            ["B"] = { type = "knight", color = "black" },
            ["C"] = { type = "bishop", color = "black" },
            ["D"] = { type = "king", color = "black" },
            ["E"] = { type = "queen", color = "black" },
            ["F"] = { type = "bishop", color = "black" },
            ["G"] = { type = "knight", color = "black" },
            ["H"] = { type = "rook", color = "black" },
        }
    }
}
